DROP TABLE SONG CASCADE CONSTRAINTS;
DROP TABLE COLLECTION CASCADE CONSTRAINTS;
DROP TABLE COLLECTION_TYPE CASCADE CONSTRAINTS;
DROP TABLE CONTRIBUTOR_ROLE CASCADE CONSTRAINTS;
DROP TABLE CONTRIBUTOR CASCADE CONSTRAINTS;

CREATE TABLE SONG (
    songid VARCHAR2(10) PRIMARY KEY,
    name VARCHAR2(30),
    song_offset NUMBER NOT NULL,
    duration_used NUMBER
    );
    
CREATE TABLE COLLECTION (
    collectionid VARCHAR2(10) PRIMARY KEY, 
    songid VARCHAR2(10) REFERENCES SONG(songid) ON DELETE CASCADE,
    release_date DATE NOT NULL,
    label VARCHAR2(30),
    market VARCHAR2(30) NOT NULL
    );
    
CREATE TABLE COLLECTION_TYPE(
    collectionid VARCHAR2(10) REFERENCES COLLECTION(collectionid) 
    ON DELETE CASCADE,
    collection_type VARCHAR2(10)
    );
    
CREATE TABLE CONTRIBUTOR_ROLE (
    roleid VARCHAR2(10) PRIMARY KEY,
    rolename VARCHAR2(20) NOT NULL
    );
    
CREATE TABLE CONTRIBUTOR(
    contributorid VARCHAR2(10) PRIMARY KEY, 
    instruments VARCHAR2(20),
    roleid VARCHAR2(10) REFERENCES ROLE(roleid) ON DELETE CASCADE
    );